[package]
authors = ["Harlan Heilman Harlan.Heilman@wsu.edu"]
description = "Core of the pyref project"
documentation = "https://docs.rs/pyref-core/latest/pyref_core/"
edition = "2021"
license = "GPL-2.0"
name = "pyref-core"
repository = "https://github.com/WSU-Carbon-Lab/pyref-ccd"
version = "0.3.3"

[lib]
name = "pyref_core"
path = "src/lib.rs"

[dependencies]
astrors = "0.1.8"
ndarray = "0.15.6"
ndarray-ndimage = "0.4.0"
numpy = "0.20.0"
physical_constants = "0.5.0"
polars-core = {version = "0.43.1", features = ["dtype-array"]}
rand = "0.8.5"
rayon = "1.10.0"

[dependencies.polars]
default-features = false
features = [
  "docs",
  "zip_with",
  "csv",
  "temporal",
  "fmt",
  "dtype-full",
]
version = "0.35.4"

[docs]
all-features = true
