[package]
authors = ["Harlan Heilman Harlan.Heilman@wsu.edu"]
description = "Core of the pyref project"
documentation = "https://docs.rs/pyref-core/latest/pyref_core/"
edition = "2021"
license = "GPL-2.0"
name = "pyref-core"
repository = "https://github.com/WSU-Carbon-Lab/pyref-ccd"
version = "0.3.44"

[lib]
name = "pyref_core"
path = "src/lib.rs"

[dependencies]
astrors-fork = "0.1.10"
chrono = "0.4.39"
image = "0.25.5"
imageproc = "0.25.0"
ndarray = "0.15.6"
numpy = "0.22.0"
physical_constants = "0.5.0"
polars = {version = "0.45.1", features = ["fmt", "dtype-u16", "lazy", "dtype-struct", "dtype-array", "dtype-datetime", "round_series"]}
polars-arrow = "0.45.1"
rayon = "1.10.0"
regex = "1.11.1"

[docs]
all-features = true
