[package]
name = "pyref-core"
version = "0.2.4"
edition = "2021"
authors = ["Harlan Heilman Harlan.Heilman@wsu.edu"]
description = "Core of the pyref project"
license = "GPL-2.0"
repository = { workspace = true }
documentation = "https://docs.rs/pyref-ccd/"

[dependencies]
astrors = "0.1.8"
ndarray = "0.15.6"


[dependencies.polars]
version = "0.42.0"
default-features = false
features = ["docs", "zip_with", "csv", "temporal", "fmt", "dtype-full"]


[lib]
name = "pyref-ccd"
path="src/pyref-ccd/lib.rs"
crate-type = ["cdylib"]

[docs]
all-features = true

# [http]
# check-revoke = false
