[package]
name = "pyref_rs"
version = "0.1.0"
edition = "2021"
authors = ["Harlan Heilman"]
description = "Rust tooling library constructed using astrors for efficient data manipulation."
license = "GPL-2.0"

[dependencies]
astrors = "0.1.8"
ndarray = "0.15.6"
polars = "0.38.3"

[lib]
crate-type = ["cdylib"]
