[package]
name = "pyref-core"
version = "0.2.13"
edition = "2021"
authors = ["Harlan Heilman Harlan.Heilman@wsu.edu"]
description = "Core of the pyref project"
license = "GPL-2.0"
repository = "https://github.com/WSU-Carbon-Lab/pyref-ccd"
documentation = "https://docs.rs/pyref-core/latest/pyref_core/"

[lib]
name = "pyref_core"
path = "src/lib.rs"

[dependencies]
astrors = "0.1.8"
ndarray = "0.15.6"

[dependencies.polars]
version = "0.42.0"
default-features = false
features = [
    "docs",
    "zip_with",
    "csv",
    "temporal",
    "fmt",
    "dtype-full",
]

[docs]
all-features = true
