[package]
name = "pyref_ccd"
version = "0.1.0"
edition = "2021"
authors = ["Harlan Heilman"]
description = "Rust library to analyze fits files from the CCD camera for the PyRef project"
license = "GPL-2.0"

[dependencies]
astrors = "0.1.8"
ndarray = "0.15.6"
polars = "0.38.3"

[lib]
crate-type = ["cdylib"]

[http]
check-revoke = false
