[package]
authors = ["Harlan Heilman Harlan.Heilman@wsu.edu"]
description = "Core of the pyref project"
documentation = "https://docs.rs/pyref-core/latest/pyref_core/"
edition = "2021"
license = "GPL-2.0"
name = "pyref-core"
repository = "https://github.com/WSU-Carbon-Lab/pyref-ccd"
version = "0.5.4"
exclude =["tests"]

[lib]
name = "pyref_core"
path = "src/lib.rs"

[dependencies]
astrors-fork = "0.1.10"
chrono = "0.4.39"
glob-match = "0.2.1"
ndarray = "0.15.6"
physical_constants = "0.5.0"
polars = {version = "0.45.1", features = ["fmt", "dtype-u16", "lazy", "dtype-struct", "dtype-array", "dtype-datetime", "round_series", "ipc", "performant"]}
rayon = "1.10.0"
thiserror = "2.0.11"
serde = {version = "1.0", features = ["derive"]}
# Optional Python bindings support
pyo3 = {version = "0.20.0", features = ["extension-module"], optional = true}

[dev-dependencies]
tempfile = "3.10.1"
rstest = "0.18.2"
predicates = "3.1.0"

[features]
default = []
python = ["pyo3"]

[docs]
all-features = true
